name: plugin_0
main: com.jano.plugin.main
version: 0.0.1
api-version: "1.19"
commands:
  jakiBlok:
    usage: "/jakiblok"
    description: wypisuje blok na ktorym stoisz
    aliases: ["whatblock"]
  stealth:
    usage: "/stealth"
    description: enter sneak mode for 30 seconds
    aliases: ["sneak"]
  feed:
    usage: "/feed"
    description: set food bar to max
  printMessageFromConfig:
    description: writes food which you can change in config file
  setFood:
    description: or you can set food here
  explode:
    description: explosion!
  repeat:
    description: Repeat stuff back to you
  spell:
    description: cast a negative spell
  setspawn:
    description: ustaw gdzie sie respisz
  spawn:
    description: tp to spawnpoint
  menu:
    description: opens menu
